language: php

php:
  - 7.0
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.local"
  - mkdocs-theme

env:
  global:
    - PHPUNIT_FLAGS: '--exclude-group=legacy'
    - SITE_URL: https://polderknowledge.github.io/log-module
    - GH_USER_NAME: "Polder Knowledge"
    - GH_USER_EMAIL: opensource@polderknowledge.nl
    - GH_REF: github.com/polderknowledge/log-module.git
    - secure: "lMU80JU7/m7vZX1cJqcBDvCYi6/yNlJbdhL4cKnkPXUmqFRdvR+CUNEknngMFHZTibAfRXzP8IbJ1IodsZcxqcF734t0yAHI836OzkrpRp8yrsPbk1QeGnG+CRt49OOqdW+P0lz+yrFNHkz3rOowcDbxsRiNWJFu4L5bF6N6Iesl6IJsEzuWD3RvXM6/0/gidSMD2UViD/J4NDf53PeMfuz6zw49HJRy+8yNjkBQRuqx6cjE+AAyd4xazZ3ZFHkW1Faot/GsFWcQBAF8j9sKWp4F+wj0NaZOvxnC6eOTw46AkOhW24j9gQ9kKizFvOCI4tDP6tI2KrlyILLzAL+Wds/kS78swaH0X72EviOIR/cA1tDSDTH1zYrMTcdh0I2W9Fan3dinZRDcG+OuH63yvUuV2LF8+GHK5MvyZ2d3Xwj7nboyBzWl+TLynyfr5VZrpDkTgVFNHJs/zWX0HJWW1osWLPNNNNX/8QK2tMNlaksEVcEl1jcyENodbG7onpGy+PvjxFJ/qKYZb6KudIml2bnQDsFN4S+GMPebCLURY16wyCNx2ASDiOsNv1p6XuwFw6Nn+P1kZb+lluHLnm/p85xRcKSWNkHKI2TCWIni873OcL56eB8lM7ZSwAsWFPWnAa2G1gdRoo4pKxD6N1hi97Gf9QlS71mM8LIga357LC8="


matrix:
  include:
  - php: 7.0
    env:
       - COMPOSER_FLAGS="--prefer-lowest"
       - PHPUNIT_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi

before_deploy:
    - mkdir -p docs/html
    - wget -O theme-installer.sh "https://raw.githubusercontent.com/polderknowledge/mkdocs-theme/master/theme-installer.sh"
    - chmod 755 theme-installer.sh
    - ./theme-installer.sh;
    - npm install -g gulp
    - ./mkdocs-theme/build.sh

deploy:
  local_dir: docs/html
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master

notifications:
  email: false
  irc: "irc.freenode.org#polderknowledge"
